### ISSUE TITLE
Question: multiple accounts

### ISSUE THREAD

**Issue by cr4zyfish** [Alexell/XEmpireBot#19]
If I have multiple telegram accounts on the same phone (Telegram allows adding up to 4 accounts). I open a dapp on one account and open the dapp also on a second account. can the app know the two accounts are from the same device? do they share the same cookies? does telegram give them some unique identifier?

**Comment by Duwaz** [comment]
> Do they share the same cookies?

I gues, not. It'll be strange for the security of Telegram.

> Does telegram give them some unique identifier?

I don't know, but let's try to think about it.
I see the next situation in the bot's logic:
1) Making a Telegram session. *Of course, they are different. Otherwise, you would have been able to read messages from another account
2) Init bot. I don't understand exactly, what it is. I see that only session info is being used. It will respond with a token (I guess it's the bot's ID. I'm not sure)
3) Login to the bot using the token. I see that there is also a string `'platform' : 'android'` sent. That's all. Maybe there is more information, but I don't see it.
*After login, we have the bot's session token and we send only it with commands to the TG bot.

Can the app request the device ID or something similar?
I googled this question and found only the answer "No". There is said that the TG bot API doesn't have this function.
You can try to find what you are looking for on this site - https://core.telegram.org/bots/api

**Comment by Alexell** [comment]
If desired, developers of any mini-app can see that different accounts are using the application from the same IP address, the same device and with the same Telegram client.
